Repository GyulyVGC/sniffnet, pull requests merged in 2023-04, with the labels that each got.

#126 v1.1.3
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  src/gui/components/radio.rs
Labels: release

#148 Iced 0.9
  Cargo.lock
  Cargo.toml
  src/gui/components/radio.rs
  src/gui/pages/initial_page.rs
  src/gui/pages/settings_notifications_page.rs
  src/gui/styles/scrollbar.rs
  src/gui/styles/slider.rs
  src/gui/styles/text_input.rs
  src/main.rs
Labels: enhancement, dependencies

#141 Update dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#151 feat: add Russian translation
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  src/translations/translations.rs
  src/translations/translations_2.rs
  src/translations/types/language.rs
  src/utils/countries.rs
Labels: translation

#134 Add portuguese translation
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  src/gui/pages/settings_language_page.rs
  src/translations/translations.rs
  src/translations/types/language.rs
  src/utils/countries.rs
Labels: translation

#157 v1.1.4
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  src/translations/translations_2.rs
Labels: release

#160 Added Greek translation
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  src/gui/pages/notifications_page.rs
  src/gui/pages/settings_style_page.rs
  src/translations/translations.rs
  src/translations/translations_2.rs
  src/translations/types/language.rs
  src/utils/countries.rs
Labels: translation
