Repository GyulyVGC/sniffnet, pull requests merged in 2023-06, with the labels that each got.

#235 Update README.md
  README.md
Labels: documentation

#241 added Romanian translation v1.2
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  src/gui/pages/settings_language_page.rs
  src/translations/translations_2.rs
Labels: translation

#244 Update polish translation
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  src/gui/pages/settings_language_page.rs
  src/translations/translations_2.rs
Labels: translation

#246 Fixed build and packaging issues
  .editorconfig
  .gitattributes
  .github/workflows/package.yml
  Cargo.lock
  Cargo.toml
  build.rs
  resources/Info.plist
  resources/logos/raw/icon.png
  resources/logos/raw/icon_macos.png
  resources/packaging/LICENSE
  resources/packaging/linux/description.txt
  resources/packaging/linux/graphics/sniffnet_1024x1024.png
  resources/packaging/linux/graphics/sniffnet_128x128.png
  resources/packaging/linux/graphics/sniffnet_160x160.png
  resources/packaging/linux/graphics/sniffnet_16x16.png
  resources/packaging/linux/graphics/sniffnet_192x192.png
  resources/packaging/linux/graphics/sniffnet_22x22.png
  resources/packaging/linux/graphics/sniffnet_24x24.png
  resources/packaging/linux/graphics/sniffnet_256x256.png
  resources/packaging/linux/graphics/sniffnet_32x32.png
  resources/packaging/linux/graphics/sniffnet_36x36.png
  resources/packaging/linux/graphics/sniffnet_384x384.png
  resources/packaging/linux/graphics/sniffnet_42x42.png
  resources/packaging/linux/graphics/sniffnet_48x48.png
  resources/packaging/linux/graphics/sniffnet_512x512.png
  resources/packaging/linux/graphics/sniffnet_64x64.png
  resources/packaging/linux/graphics/sniffnet_72x72.png
  resources/packaging/linux/graphics/sniffnet_8x8.png
  resources/packaging/linux/graphics/sniffnet_96x96.png
  resources/packaging/linux/scripts/.gitkeep
  resources/packaging/linux/scripts/postinst
  resources/packaging/linux/scripts/prerm
  resources/packaging/linux/sniffnet.desktop
  resources/packaging/macos/Info.plist
  resources/packaging/macos/graphics/dmg_bg.png
  resources/packaging/macos/graphics/sniffnet.icns
  resources/packaging/macos/wrapper.sh
  resources/packaging/windows/EULA.rtf
  resources/packaging/windows/graphics/banner.bmp
  resources/packaging/windows/graphics/dialog.bmp
  resources/packaging/windows/graphics/sniffnet.ico
  resources/packaging/windows/setup.wxs
  resources/wrapper.sh
  wix/main.wxs
Labels: enhancement

#259 Finalising the new packaging strategy
  .editorconfig
  .gitattributes
  .github/workflows/package.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  build.rs
  resources/Info.plist
  resources/logos/raw/icon.png
  resources/logos/raw/icon_macos.png
  resources/packaging/LICENSE
  resources/packaging/linux/description.txt
  resources/packaging/linux/graphics/sniffnet_1024x1024.png
  resources/packaging/linux/graphics/sniffnet_128x128.png
  resources/packaging/linux/graphics/sniffnet_160x160.png
  resources/packaging/linux/graphics/sniffnet_16x16.png
  resources/packaging/linux/graphics/sniffnet_192x192.png
  resources/packaging/linux/graphics/sniffnet_22x22.png
  resources/packaging/linux/graphics/sniffnet_24x24.png
  resources/packaging/linux/graphics/sniffnet_256x256.png
  resources/packaging/linux/graphics/sniffnet_32x32.png
  resources/packaging/linux/graphics/sniffnet_36x36.png
  resources/packaging/linux/graphics/sniffnet_384x384.png
  resources/packaging/linux/graphics/sniffnet_42x42.png
  resources/packaging/linux/graphics/sniffnet_48x48.png
  resources/packaging/linux/graphics/sniffnet_512x512.png
  resources/packaging/linux/graphics/sniffnet_64x64.png
  resources/packaging/linux/graphics/sniffnet_72x72.png
  resources/packaging/linux/graphics/sniffnet_8x8.png
  resources/packaging/linux/graphics/sniffnet_96x96.png
  resources/packaging/linux/scripts/.gitkeep
  resources/packaging/linux/scripts/postinst
  resources/packaging/linux/scripts/prerm
  resources/packaging/linux/sniffnet.desktop
  resources/packaging/macos/Info.plist
  resources/packaging/macos/graphics/dmg_bg.png
  resources/packaging/macos/graphics/sniffnet.icns
  resources/packaging/macos/wrapper.sh
  resources/packaging/windows/EULA.rtf
  resources/packaging/windows/graphics/banner.bmp
  resources/packaging/windows/graphics/dialog.bmp
  resources/packaging/windows/graphics/sniffnet.ico
  resources/packaging/windows/setup.wxs
  resources/wrapper.sh
  src/countries/country_utils.rs
  src/notifications/types/notifications.rs
  src/translations/types/language.rs
  wix/main.wxs
Labels: enhancement, release

#271 Update translations_2.rs
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  src/translations/translations_2.rs
Labels: translation

#272 feat: support --help and --version CLI arguments
  src/cli/mod.rs
  src/main.rs
  src/networking/types/data_info.rs
Labels: enhancement

#279 Update translations_2.rs
  src/gui/pages/settings_language_page.rs
  src/translations/translations_2.rs
Labels: translation

#285 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation
