Repository GyulyVGC/sniffnet, pull requests merged in 2023-08, with the labels that each got.

#330 Minimal custom themes implementation
  src/chart/manage_chart_data.rs
  src/chart/types/traffic_chart.rs
  src/configs/types/config_settings.rs
  src/gui/pages/settings_style_page.rs
  src/gui/styles/button.rs
  src/gui/styles/container.rs
  src/gui/styles/custom_themes/dracula.rs
  src/gui/styles/custom_themes/gruvbox.rs
  src/gui/styles/custom_themes/mod.rs
  src/gui/styles/custom_themes/nord.rs
  src/gui/styles/custom_themes/solarized.rs
  src/gui/styles/mod.rs
  src/gui/styles/picklist.rs
  src/gui/styles/rule.rs
  src/gui/styles/scrollbar.rs
  src/gui/styles/style_constants.rs
  src/gui/styles/text.rs
  src/gui/styles/text_input.rs
  src/gui/styles/types/custom_palette.rs
  src/gui/styles/types/mod.rs
  src/gui/styles/types/palette.rs
  src/gui/styles/types/style_type.rs
  src/gui/types/sniffer.rs
Labels: design

#335 v1.2.2
  .all-contributorsrc
  CHANGELOG.md
  CONTRIBUTORS.md
  Cargo.lock
  Cargo.toml
  README.md
  ROADMAP.md
  src/chart/manage_chart_data.rs
  src/chart/types/traffic_chart.rs
  src/configs/types/config_settings.rs
  src/gui/pages/settings_style_page.rs
  src/gui/styles/button.rs
  src/gui/styles/container.rs
  src/gui/styles/custom_themes/dracula.rs
  src/gui/styles/custom_themes/gruvbox.rs
  src/gui/styles/custom_themes/mod.rs
  src/gui/styles/custom_themes/nord.rs
  src/gui/styles/custom_themes/solarized.rs
  src/gui/styles/mod.rs
  src/gui/styles/picklist.rs
  src/gui/styles/rule.rs
  src/gui/styles/scrollbar.rs
  src/gui/styles/style_constants.rs
  src/gui/styles/text.rs
  src/gui/styles/text_input.rs
  src/gui/styles/types/custom_palette.rs
  src/gui/styles/types/mod.rs
  src/gui/styles/types/palette.rs
  src/gui/styles/types/style_type.rs
  src/gui/types/sniffer.rs
Labels: release

#339 First-class theming
  src/chart/types/traffic_chart.rs
  src/countries/country_utils.rs
  src/gui/app.rs
  src/gui/components/footer.rs
  src/gui/components/header.rs
  src/gui/components/modal.rs
  src/gui/components/radio.rs
  src/gui/components/tab.rs
  src/gui/pages/connection_details_page.rs
  src/gui/pages/initial_page.rs
  src/gui/pages/inspect_page.rs
  src/gui/pages/notifications_page.rs
  src/gui/pages/overview_page.rs
  src/gui/pages/settings_language_page.rs
  src/gui/pages/settings_notifications_page.rs
  src/gui/pages/settings_style_page.rs
  src/gui/pages/types/running_page.rs
  src/gui/pages/types/settings_page.rs
  src/gui/styles/button.rs
  src/gui/styles/checkbox.rs
  src/gui/styles/container.rs
  src/gui/styles/mod.rs
  src/gui/styles/picklist.rs
  src/gui/styles/radio.rs
  src/gui/styles/rule.rs
  src/gui/styles/scrollbar.rs
  src/gui/styles/slider.rs
  src/gui/styles/svg.rs
  src/gui/styles/text.rs
  src/gui/styles/text_input.rs
  src/gui/styles/types/style_type.rs
  src/report/get_report_entries.rs
  src/report/types/mod.rs
  src/report/types/report_entry.rs
  src/translations/translations.rs
  src/translations/types/language.rs
  src/utils/formatted_strings.rs
Labels: enhancement

#341 Update README.md
  README.md
Labels: documentation

#343 Japanese translation added
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  src/gui/pages/settings_language_page.rs
  src/translations/translations.rs
  src/translations/translations_2.rs
  src/translations/types/language.rs
Labels: translation

#356 fix build failure on powerpc64
  Cargo.lock
  Cargo.toml
Labels: dependencies
