Repository GyulyVGC/sniffnet, pull requests merged in 2024-02, with the labels that each got.

#450 Support more upper layer services (many, many, many more)
  .gitignore
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  build.rs
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  services.sh
  services.txt
  src/gui/pages/connection_details_page.rs
  src/gui/pages/initial_page.rs
  src/gui/pages/inspect_page.rs
  src/gui/pages/overview_page.rs
  src/gui/types/message.rs
  src/gui/types/sniffer.rs
  src/main.rs
  src/networking/manage_packets.rs
  src/networking/types/app_protocol.rs
  src/networking/types/data_info_host.rs
  src/networking/types/info_address_port_pair.rs
  src/networking/types/info_traffic.rs
  src/networking/types/ip_version.rs
  src/networking/types/mod.rs
  src/networking/types/protocol.rs
  src/networking/types/service.rs
  src/networking/types/service_query.rs
  src/notifications/notify_and_log.rs
  src/notifications/types/notifications.rs
  src/report/get_report_entries.rs
  src/report/types/mod.rs
  src/report/types/report_col.rs
  src/report/types/search_parameters.rs
  src/secondary_threads/parse_packets.rs
  src/translations/translations.rs
  src/translations/translations_2.rs
  src/translations/translations_3.rs
Labels: enhancement

#452 Sort options for Host & Service columns in overview page
  CHANGELOG.md
  src/gui/pages/overview_page.rs
  src/gui/types/message.rs
  src/gui/types/sniffer.rs
  src/networking/types/data_info.rs
  src/report/get_report_entries.rs
  src/report/types/report_sort_type.rs
  src/report/types/search_parameters.rs
  src/report/types/sort_type.rs
Labels: enhancement

#454 doc: Correct and enhance Spanish translation
  CHANGELOG.md
  src/gui/pages/inspect_page.rs
  src/translations/translations_2.rs
  src/translations/translations_3.rs
Labels: translation

#461 Use smoother curves to interpolate traffic chart data points
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/chart/manage_chart_data.rs
  src/chart/types/traffic_chart.rs
  src/gui/pages/connection_details_page.rs
  src/gui/pages/inspect_page.rs
  src/gui/pages/notifications_page.rs
  src/gui/pages/overview_page.rs
  src/gui/pages/settings_notifications_page.rs
  src/gui/types/runtime_data.rs
  src/gui/types/sniffer.rs
  src/networking/types/byte_multiple.rs
  src/networking/types/info_traffic.rs
  src/notifications/notify_and_log.rs
  src/notifications/types/notifications.rs
  src/report/types/report_col.rs
  src/utils/formatted_strings.rs
Labels: design
