Repository GyulyVGC/sniffnet, pull requests merged in 2024-12, with the labels that each got.

#645 Redirect `stderr` and `stdout` to file on Windows releases
  .github/workflows/package.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/cli/mod.rs
  src/main.rs
  src/utils/formatted_strings.rs
Labels: bug, enhancement, Windows

#652 Confirm quitting the app during an ongoing analysis
  CHANGELOG.md
  src/gui/components/modal.rs
  src/gui/components/types/my_modal.rs
  src/gui/sniffer.rs
  src/gui/types/message.rs
Labels: enhancement

#660 misspell fix DE
  CHANGELOG.md
  src/translations/translations_3.rs
Labels: translation
