Repository GyulyVGC/sniffnet, pull requests merged in 2025-04, with the labels that each got.

#776 Incorporate feedbacks from ROS security audit
  CHANGELOG.md
  src/gui/sniffer.rs
  src/gui/types/export_pcap.rs
Labels: enhancement

#774 Add zh_TW Traditional Chinese translation
  CHANGELOG.md
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  src/gui/pages/inspect_page.rs
  src/report/types/report_col.rs
  src/translations/translations.rs
  src/translations/translations_2.rs
  src/translations/translations_3.rs
  src/translations/translations_4.rs
  src/translations/types/language.rs
Labels: translation

#784 Error handling to reduce the number of possible crash occurrences
  CHANGELOG.md
  src/chart/types/traffic_chart.rs
  src/gui/pages/connection_details_page.rs
  src/gui/pages/initial_page.rs
  src/gui/pages/overview_page.rs
  src/gui/pages/settings_general_page.rs
  src/gui/pages/settings_notifications_page.rs
  src/gui/sniffer.rs
  src/main.rs
  src/mmdb/types/mmdb_reader.rs
  src/networking/manage_packets.rs
  src/networking/types/capture_context.rs
  src/networking/types/ip_collection.rs
  src/networking/types/my_link_type.rs
  src/networking/types/packet_filters_fields.rs
  src/networking/types/port_collection.rs
  src/notifications/notify_and_log.rs
  src/notifications/types/notifications.rs
  src/notifications/types/sound.rs
  src/report/get_report_entries.rs
  src/report/types/search_parameters.rs
  src/secondary_threads/parse_packets.rs
  src/utils/error_logger.rs
  src/utils/formatted_strings.rs
  src/utils/mod.rs
Labels: enhancement

#785 Add new themes optimised for Accessibility
  CHANGELOG.md
  resources/themes/sniffnet_rebrand.toml
  src/configs/types/config_device.rs
  src/configs/types/config_settings.rs
  src/configs/types/config_window.rs
  src/gui/sniffer.rs
  src/gui/styles/container.rs
  src/gui/styles/custom_themes/a11y.rs
  src/gui/styles/types/style_type.rs
Labels: enhancement, design
