Repository GyulyVGC/sniffnet, pull requests merged in 2025-05, with the labels that each got.

#735 feat: docker container
  .dockerignore
  .github/workflows/docker.yml
  .gitignore
  Dockerfile
  README.md
Labels: enhancement

#799 Test Docker image
  .dockerignore
  .github/workflows/docker.yml
  .gitignore
  CHANGELOG.md
  Dockerfile
  README.md
Labels: enhancement

#611 Indonesian translation 🇮🇩
  CHANGELOG.md
  src/gui/pages/inspect_page.rs
  src/translations/translations.rs
  src/translations/translations_2.rs
  src/translations/translations_3.rs
  src/translations/types/language.rs
Labels: translation

#806 Use asynchronous channels to update app state from backend
  .github/workflows/docker.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/chart/manage_chart_data.rs
  src/chart/types/traffic_chart.rs
  src/cli/mod.rs
  src/configs/types/config_device.rs
  src/gui/components/footer.rs
  src/gui/components/header.rs
  src/gui/pages/connection_details_page.rs
  src/gui/pages/initial_page.rs
  src/gui/pages/inspect_page.rs
  src/gui/pages/notifications_page.rs
  src/gui/pages/overview_page.rs
  src/gui/pages/settings_general_page.rs
  src/gui/pages/settings_notifications_page.rs
  src/gui/pages/settings_style_page.rs
  src/gui/pages/thumbnail_page.rs
  src/gui/sniffer.rs
  src/gui/styles/types/palette.rs
  src/gui/types/message.rs
  src/gui/types/mod.rs
  src/gui/types/runtime_data.rs
  src/main.rs
  src/networking/manage_packets.rs
  src/networking/mod.rs
  src/networking/parse_packets.rs
  src/networking/types/arp_type.rs
  src/networking/types/capture_context.rs
  src/networking/types/data_info.rs
  src/networking/types/data_info_host.rs
  src/networking/types/host.rs
  src/networking/types/host_data_states.rs
  src/networking/types/icmp_type.rs
  src/networking/types/info_address_port_pair.rs
  src/networking/types/info_traffic.rs
  src/networking/types/my_device.rs
  src/notifications/notify_and_log.rs
  src/report/get_report_entries.rs
  src/secondary_threads/mod.rs
  src/secondary_threads/parse_packets.rs
  src/utils/check_updates.rs
  src/utils/formatted_strings.rs
  src/utils/mod.rs
  src/utils/types/icon.rs
  src/utils/types/mod.rs
  src/utils/types/timestamp.rs
Labels: enhancement, iced

#777 Apply new notification thresholds only after timeout expires
  CHANGELOG.md
  src/gui/pages/settings_notifications_page.rs
  src/gui/sniffer.rs
  src/gui/types/timing_events.rs
  src/notifications/types/notifications.rs
Labels: enhancement
