Repository GyulyVGC/sniffnet, pull requests merged in 2025-02, with the labels that each got.

#690 Translation Update - PT
  CHANGELOG.md
  src/translations/translations_3.rs
  src/translations/translations_4.rs
  src/translations/types/language.rs
Labels: translation

#692 Add Ukrainian translation for version 1.3.
  CHANGELOG.md
  resources/fonts/full/subset_characters.txt
  resources/fonts/subset/sarasa-mono-sc-bold.subset.ttf
  resources/fonts/subset/sarasa-mono-sc-regular.subset.ttf
  src/translations/translations.rs
  src/translations/translations_2.rs
  src/translations/translations_3.rs
  src/translations/translations_4.rs
  src/translations/types/language.rs
Labels: translation

#708 Create the new theme sniff_oled.toml
  CHANGELOG.md
  src/gui/styles/custom_themes/mod.rs
  src/gui/styles/custom_themes/oled.rs
  src/gui/styles/types/custom_palette.rs
Labels: design

#718 Fix Sniffnet `crates.io` package for Windows
  .github/workflows/package.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  build.rs
Labels: bug, enhancement, Windows

#719 Add icon to window title bar
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  build.rs
  src/main.rs
Labels: enhancement

#720 Show more information when domain name is short
  CHANGELOG.md
  src/utils/formatted_strings.rs
Labels: enhancement
