Repository GyulyVGC/sniffnet, pull requests merged in 2025-08, with the labels that each got.

#849 Add japanese translations for v4
  src/translations/translations_4.rs
Labels: translation

#859 Add AppImage Packaging to CI
  .github/workflows/package.yml
  CHANGELOG.md
  resources/packaging/linux/AppImage/sniffnet.yml
Labels: enhancement, Linux, packaging

#936 Add bits data representation
  CHANGELOG.md
  src/chart/manage_chart_data.rs
  src/chart/types/chart_type.rs
  src/chart/types/donut_chart.rs
  src/chart/types/mod.rs
  src/chart/types/traffic_chart.rs
  src/gui/pages/connection_details_page.rs
  src/gui/pages/inspect_page.rs
  src/gui/pages/notifications_page.rs
  src/gui/pages/overview_page.rs
  src/gui/pages/settings_notifications_page.rs
  src/gui/pages/thumbnail_page.rs
  src/gui/sniffer.rs
  src/gui/types/message.rs
  src/main.rs
  src/networking/types/byte_multiple.rs
  src/networking/types/data_info.rs
  src/networking/types/data_representation.rs
  src/networking/types/info_address_port_pair.rs
  src/networking/types/info_traffic.rs
  src/networking/types/mod.rs
  src/notifications/notify_and_log.rs
  src/notifications/types/logged_notification.rs
  src/notifications/types/notifications.rs
  src/report/get_report_entries.rs
  src/report/types/report_col.rs
  src/report/types/report_sort_type.rs
  src/translations/translations_2.rs
  src/translations/translations_4.rs
Labels: enhancement

#937 Improve filtering capabilities: Berkeley Packet Filter
  CHANGELOG.md
  src/chart/manage_chart_data.rs
  src/chart/types/donut_chart.rs
  src/chart/types/traffic_chart.rs
  src/gui/pages/initial_page.rs
  src/gui/pages/overview_page.rs
  src/gui/pages/settings_notifications_page.rs
  src/gui/pages/thumbnail_page.rs
  src/gui/sniffer.rs
  src/gui/styles/button.rs
  src/gui/styles/donut.rs
  src/gui/styles/rule.rs
  src/gui/styles/text_input.rs
  src/gui/types/filters.rs
  src/gui/types/message.rs
  src/gui/types/mod.rs
  src/networking/manage_packets.rs
  src/networking/parse_packets.rs
  src/networking/types/bogon.rs
  src/networking/types/capture_context.rs
  src/networking/types/filters.rs
  src/networking/types/info_traffic.rs
  src/networking/types/ip_collection.rs
  src/networking/types/ip_version.rs
  src/networking/types/mod.rs
  src/networking/types/my_link_type.rs
  src/networking/types/port_collection.rs
  src/networking/types/protocol.rs
  src/translations/mod.rs
  src/translations/translations.rs
  src/translations/translations_3.rs
  src/translations/translations_4.rs
  src/translations/translations_5.rs
  src/utils/formatted_strings.rs
  src/utils/types/icon.rs
Labels: enhancement

#938 Improve configurations persistence across different runs of the app
  CHANGELOG.md
  src/cli/mod.rs
  src/configs/mod.rs
  src/configs/types/config_device.rs
  src/configs/types/config_settings.rs
  src/configs/types/configs.rs
  src/configs/types/mod.rs
  src/gui/components/header.rs
  src/gui/pages/connection_details_page.rs
  src/gui/pages/initial_page.rs
  src/gui/pages/inspect_page.rs
  src/gui/pages/notifications_page.rs
  src/gui/pages/overview_page.rs
  src/gui/pages/settings_general_page.rs
  src/gui/pages/settings_notifications_page.rs
  src/gui/pages/settings_style_page.rs
  src/gui/pages/thumbnail_page.rs
  src/gui/pages/types/running_page.rs
  src/gui/pages/types/settings_page.rs
  src/gui/sniffer.rs
  src/gui/types/conf.rs
  src/gui/types/config_window.rs
  src/gui/types/export_pcap.rs
  src/gui/types/filters.rs
  src/gui/types/message.rs
  src/gui/types/mod.rs
  src/gui/types/settings.rs
  src/main.rs
  src/networking/types/capture_context.rs
  src/networking/types/config_device.rs
  src/networking/types/mod.rs
  src/notifications/types/notifications.rs
  src/report/get_report_entries.rs
  src/report/types/mod.rs
  src/report/types/report_sort_type.rs
  src/report/types/sort_type.rs
Labels: enhancement
